server:
  port: 7272

spring:
  datasource:
    # Path is relative to java-api/ when running locally
    url: jdbc:sqlite:../data/market.db
    driver-class-name: org.sqlite.JDBC

management:
  endpoints:
    web:
      exposure:
        include: health,metrics